/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_SodiumJni */

#ifndef _Included_example_SodiumJni
#define _Included_example_SodiumJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_SodiumJni
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_example_SodiumJni_print
  (JNIEnv *, jobject);

/*
 * Class:     example_SodiumJni
 * Method:    jni_crypto_scalarmult_curve25519
 * Signature: ([B[B[B)I
 */
JNIEXPORT jint JNICALL Java_example_SodiumJni_jni_1crypto_1scalarmult_1curve25519
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     example_SodiumJni
 * Method:    jni_crypto_scalarmult_curve25519_base
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_example_SodiumJni_jni_1crypto_1scalarmult_1curve25519_1base
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
